pr:
  - features/*
  - develop/*

trigger:
  - main

variables:
  - name: 'Main.Branch'
    value: refs/heads/main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    displayName: Build and test
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      options: '-T 2C -B -Drevision=$(Build.BuildNumber)'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: '1.11'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: server

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: server
      tags: |
        0.0-$(Build.BuildNumber).0
    condition: ne(variables['Build.SourceBranch'], variables['Main.Branch'])

  - task: Docker@2
    displayName: Build and Push ($(Main.Branch))
    inputs:
      command: buildAndPush
      repository: server
      tags: |
        latest
    condition: eq(variables['Build.SourceBranch'], variables['Main.Branch'])
