pr:
  - features/*

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    displayName: Build and test
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      options: '-T 2C -B'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: '1.11'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: 'Docker Hub'

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: domaly/server
      tags: |
        0.0-$(Build.BuildNumber).0
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main'))

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: domaly/server
      tags: |
        latest
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main'))
