pr:
  - features/*

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    displayName: Build and test
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      options: '-T 2C -B'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      jdkVersionOption: '1.11'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: dockerhub

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: server
      tags: |
        $(build_number)
        latest
