spring:
  datasource:
    url: jdbc:mysql://localhost:6603/lw?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: lwuser
    password: lwpassword

gradation:
  junior: 5
  middle: 10
  senior: 15
